### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by D-Bhatta** [Takishima/flake8-secure-coding-standard#31]
Running the [flake8-secure-coding-standard](https://github.com/Takishima/flake8-secure-coding-standard) plugin with flake8 raises the exception `AttributeError: 'Attribute' object has no attribute 'id'`.
Here is the traceback:

```bash
❯ flake8 app/bandit_check.py 
Traceback (most recent call last):
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 364, in _run 
    self.run_checks()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 311, in run
    self.run_serial()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 295, in run_serial    
    checker.run_checks()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 500, in run_ast_checks    for (line_number, offset, text, _) in runner:
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py", line 358, in run
    visitor.visit(self._tree)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 420, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py", line 261, in visit_Call
    elif _is_yaml_unsafe_call(node):
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py", line 214, in _is_yaml_unsafe_call
    if len(node.args) < 2 or (node.args[1].id in _unsafe_loaders):
AttributeError: 'Attribute' object has no attribute 'id'
```

## Additional context

Here is the `.flake8` file I am using for config:

```ini
[flake8]
max-line-length = 88
color = always
extend-exclude = tests/
extend-ignore =
    D203,
    E203,
    # Supressed for duplicating flake8-bugbear warning
    E501,
    # Supressed for bugbear
    E722
    # Supressed for lowering performance
    SIM105
extend-select =
    B9,
    DUO

```

Here is the file I am running it on:

```python
# bandit_check.py
from typing import Any
import yaml


class YamlOps:
    """Perform operations on YAML"""

    @classmethod
    def convert_to_yaml(cls, yaml_dict: dict[str, str]) -> Any:
        """Serialize a Dict[str, str] to YAML string"""
        return yaml.dump(yaml_dict)

    @classmethod
    def convert_from_yaml(cls, yaml_string: str) -> Any:
        """Convert a YAML string to YAML object"""
        return yaml.load(yaml_string, yaml.Loader)


yaml_serialized = YamlOps.convert_to_yaml(
    {
        "layout": "post",
        "title": "Getting Started with Bandit",
        "date": "2017-01-16",
        "author": "Ian Cordasco",
    }
)
parsed_yaml = YamlOps.convert_from_yaml(yaml_string=yaml_serialized)

```

Uninstalling flake8_secure_coding_standard solves the issue.

```bash
Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) 
❯ pip install flake8_secure_coding_standard
Collecting flake8_secure_coding_standard
  Using cached flake8_secure_coding_standard-1.2.1-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: flake8>=3.7 in ./.venv/lib/python3.10/site-packages (from flake8_secure_coding_standard) (4.0.1)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in ./.venv/lib/python3.10/site-packages (from flake8>=3.7->flake8_secure_coding_standard) (2.4.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./.venv/lib/python3.10/site-packages (from flake8>=3.7->flake8_secure_coding_standard) (0.6.1)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in ./.venv/lib/python3.10/site-packages (from flake8>=3.7->flake8_secure_coding_standard) (2.8.0)
Installing collected packages: flake8_secure_coding_standard
Successfully installed flake8_secure_coding_standard-1.2.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the '/mnt/j/Education/Code/Python/Python-Files/.venv/bin/python3.10 -m pip install --upgrade pip' 
command.

Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) took 7s 
❯ flake8 app/bandit_check.py 
Traceback (most recent call last):
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 364, in _run 
    self.run_checks()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 311, in run
    self.run_serial()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 295, in run_serial    
    checker.run_checks()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8/checker.py", line 500, in run_ast_checks    for (line_number, offset, text, _) in runner:
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py", line 358, in run
    visitor.visit(self._tree)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 420, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py", line 261, in visit_Call
    elif _is_yaml_unsafe_call(node):
  File "/mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py", line 214, in _is_yaml_unsafe_call
    if len(node.args) < 2 or (node.args[1].id in _unsafe_loaders):
AttributeError: 'Attribute' object has no attribute 'id'

Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) took 6s 
❯ pip uninstall flake8_secure_coding_standard
Found existing installation: flake8-secure-coding-standard 1.2.1
Uninstalling flake8-secure-coding-standard-1.2.1:
  Would remove:
    /mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard-1.2.1.dist-info/*    
    /mnt/j/Education/Code/Python/Python-Files/.venv/lib/python3.10/site-packages/flake8_secure_coding_standard.py
Proceed (Y/n)? y
  Successfully uninstalled flake8-secure-coding-standard-1.2.1

Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) took 11s 
❯ flake8 app/bandit_check.py
app/bandit_check.py:12:16: DUO109 insecure use of "yaml" parsing function, prefer "safe_*" equivalent
app/bandit_check.py:17:16: DUO109 insecure use of "yaml" parsing function, prefer "safe_*" equivalent

Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) 
❯ flake8 --version
4.0.1 (dlint: 0.12.0, flake8-bugbear: 22.4.25, flake8-comprehensions: 3.10.0, flake8_simplify: 0.19.2, mccabe: 0.6.1, pycodestyle:
2.8.0, pyflakes: 2.4.0) CPython 3.10.4 on Linux

Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) 
❯
```
Here is pip freeze:

```shell
Python-Files on  main [!?] via 🐍 v3.10.4 (.venv) 
❯ pip freeze
astor==0.8.1
astroid==2.11.5
attrs==21.4.0
bandit==1.7.4
black==22.3.0
cfgv==3.3.1
click==8.1.3
dill==0.3.5.1
distlib==0.3.4
dlint==0.12.0
filelock==3.7.0
flake8==4.0.1
flake8-bugbear==22.4.25
flake8-comprehensions==3.10.0
flake8-simplify==0.19.2
gitdb==4.0.9
GitPython==3.1.27
identify==2.5.1
iniconfig==1.1.1
isort==5.10.1
lazy-object-proxy==1.7.1
mccabe==0.6.1
mypy==0.950
mypy-extensions==0.4.3
nodeenv==1.6.0
packaging==21.3
pathspec==0.9.0
pbr==5.9.0
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.19.0
py==1.11.0
pycodestyle==2.8.0
pyflakes==2.4.0
pylint==2.13.9
pyparsing==3.0.9
pytest==7.1.2
PyYAML==6.0
six==1.16.0
smmap==5.0.0
stevedore==3.5.0
toml==0.10.2
tomli==2.0.1
typing_extensions==4.2.0
virtualenv==20.14.1
wrapt==1.14.1
```

**Comment by Takishima** [comment]
Thanks for reporting this issue. I have a fix that should be ready in a bit.
